//package com.gft.staffwa.models;
//
//import lombok.AllArgsConstructor;
//import lombok.Getter;
//import lombok.NoArgsConstructor;
//import lombok.ToString;
//
//@AllArgsConstructor
//@NoArgsConstructor
//@ToString
//public enum EnumNomeTecnologia {
//
//  A_GRAPHICS_LANGUAGE("A Graphics Language"), A_SHARP("A#"), A_PLUS("A+ (linguagem de programação)"),
//  A_PLUS_PLUS("A++"), ABAP("ABAP"), ABBREVIATED_LANGUAGE_FOR_AUTHORIZATION("Abbreviated Language For Authorization"),
//  ABBREVIATED_TEST_LANGUAGE_FOR_ALL_SYSTEMS("Abbreviated Test Language for All Systems"), ABC("ABC"), ABLE("ABLE"),
//  ABSET("ABSET"), ABSTRACT_STATE_MACHINE_LANGUAGE("Abstract State Machine Language"),
//  ABSTRACT_TYPE_AND_SCHEME_DEFINITION_LANGUAGE("Abstract-Type and Scheme-Definition Language"), ABSYS("ABSYS"),
//  ACCENT("Accent"), ACL2("ACL2"), ACTION("Action!"), ACTIONSCRIPT("ActionScript"), ACTIVE_OBERON("Active Oberon"),
//  ACTIVEBASIC("ActiveBasic"), ACTIVEVFP("ActiveVFP"), ACTOR("Actor"),
//  ACTOR_BASED_CONCURRENT_LANGUAGE("Actor-Based Concurrent Language"), ACUCOBOL("ACUCOBOL"), ADA("Ada"),
//  ADA_2005("Ada 2005"), ADA_2012("Ada 2012"), ADA_2020("Ada 2020"), ADA_83("Ada 83"), ADA_95("Ada 95"),
//  ADDRESS_PROGRAMMING_LANGUAGE("Address programming language"), ADENINE("adenine"), ADMB("ADMB"),
//  ADVANCED_BUSINESS_APPLICATION_LANGUAGE("Advanced Business Application Language"),
//  ADVENTURE_DEFINITION_LANGUAGE("Adventure Definition Language"), ADVICE_TAKER("Advice taker"), ADVPL("ADVPL"),
//  AGDA("Agda"), AGENTSHEETS("AgentSheets"), AGENTSPEAK("AgentSpeak"), AGILENT_VEE("Agilent VEE"), AGORA("Agora"),
//  AIMMS("AIMMS"), AIRELLE("Airelle"), ALCOR("ALCOR"), ALDOR("Aldor"), ALEF("Alef"), ALEPH("Aleph"), ALGAE("ALGAE"),
//  ALGEBRAIC_LOGIC_FUNCTIONAL_PROGRAMMING_LANGUAGE("Algebraic Logic Functional programming language"),
//  ALGEBRAIC_SEMANTICS("Algebraic semantics"), ALGEK("Algek"), ALGOL("ALGOL"), ALGOL_58("ALGOL 58"),
//  ALGOL_60("ALGOL 60"), ALGOL_68("ALGOL 68"), ALGOL_W("Algol-W"), ALICE("Alice"),
//  ALLEGRO_COMMON_LISP("Allegro Common Lisp"), ALMA_0("Alma-0"), ALPHA("Alpha"), ALPHARD("Alphard"),
//  ALTAIR_BASIC("Altair BASIC"), ALTERA_HARDWARE_DESCRIPTION_LANGUAGE("Altera Hardware Description Language"),
//  ALTRAN("ALTRAN"), ALUSUS("Alusus"), AMBER("Amber"), AMBIENTTALK("AmbientTalk"), AMBIT("AMBIT"), AMIBLITZ("AmiBlitz"),
//  AMIGABASIC("AmigaBASIC"), AMIGAE("AmigaE"), AMOS("AMOS"), AMPL("AMPL"), AMPLE("AMPLE"), ANA("Ana"),
//  ANALYTICA("Analytica"), ANALYTICAL_ENGINE_ORDER_CODE("Analytical Engine order code"),
//  ANSI_ISO_C_SPECIFICATION_LANGUAGE("ANSI/ISO C Specification Language"),
//  ANSYS_PARAMETRIC_DESIGN_LANGUAGE("ANSYS Parametric Design Language"), ARC("Arc"), ARC_ASSEMBLY("ARC Assembly"),
//  ARDUINO_LANGUAGE("Arduino language"), ARENDELLE("Arendelle"), ARGUS("Argus"), ARITH_MATIC("ARITH-MATIC"),
//  ARLA("ARLA"), ARLOGO("ARLOGO"), ARMSCRIPT("ArmScript"), ARS_PLUS_PLUS("ARS++"), ASCEND("ASCEND"),
//  ASIC("ASIC (linguagem de programação)"), ASM_DOTJS("asm.js"), ASP("ASP"), ASP_DOTNET("ASP.NET"),
//  ASPECTC_PLUS_PLUS("AspectC++"), ASPECTJ("AspectJ"), ASSEMBLY("assembly"), ASTEK("Astek"), ASYMPTOTE("Asymptote"),
//  AT_T("AT&T"), ATARI_BASIC("Atari BASIC"), ATARI_LOGO("Atari LOGO"), ATARI_MICROSOFT_BASIC("Atari Microsoft BASIC"),
//  ATEJI_PX("Ateji PX"), ATLAS_AUTOCODE("Atlas Autocode"),
//  ATLAS_TRANSFORMATION_LANGUAGE("ATLAS Transformation Language"), ATOLL("ATOLL"), ATOM("Atom"), ATS("ATS"),
//  AUTOCODE("Autocode"), AUTOLISP("AutoLISP"), AUTOMATICALLY_PROGRAMMED_TOOL("Automatically Programmed Tool"),
//  AVEREST("Averest"), AXUM("Axum"), B("B"), B4X("B4X"), BABBAGE("Babbage"), BABY_MODULA_3("Baby modula-3"),
//  BACAIC("BACAIC"), BALLERINA("Ballerina"), BALTAZAR("Baltazar"),
//  BANCSTAR_PROGRAMMING_LANGUAGE("BANCStar programming language"), BASIC("BASIC"), BASIC_8("BASIC 8"),
//  BASIC_FOR_QT("Basic For Qt"), BASIC_SOUND_EXTENSION("Basic Sound Extension"), BASIC09("BASIC09"),
//  BASIC4ANDROID("Basic4android"), BASIC4GL("Basic4GL"), BASIC4PPC("Basic4ppc"), BATCH("batch"), BBC_BASIC("BBC BASIC"),
//  BBJ("BBj"), BBN_LISP("BBN LISP"), BC("bc"), BCPL("BCPL"), BEANSHELL("BeanShell"), BEATNIK("Beatnik"),
//  BEFLIX("BEFLIX"), BEFUNGE("Befunge"), BEHAVIORAL_DESCRIPTION_LANGUAGE("Behavioral Description Language"),
//  BERTRAND("Bertrand"), BETA("BETA"), BIDULE("Bidule"), BIO7("Bio7"), BIRKBECK_ASSEMBLER("Birkbeck Assembler"),
//  BISTRO("Bistro (linguagem de programação)"), BITC("BitC"), BLA("Bla"), BLISS("BLISS"), BLITZ_BASIC("Blitz Basic"),
//  BLITZ2D("Blitz2D"), BLITZ3D("Blitz3D"), BLITZMAX("BlitzMax"), BLITZPLUS("BlitzPlus"), BLOCKLY("Blockly"),
//  BLOOM("Bloom"), BLOOP_AND_FLOOP("BlooP and FlooP"), BLUB("Blub"), BLUE("Blue"),
//  BOEHM_UNNAMED_CODING_SYSTEM("Boehm unnamed coding system"), BON("Bon (linguagem de programação)"), BOO("Boo"),
//  BOOMERANG("Boomerang"), BOURNE_SHELL("Bourne shell"), BRAINFUCK("Brainfuck"), BRIEF_CODE("Brief Code"),
//  BRUTUS2D("Brutus2D"), BUSINESS_INTELLIGENCE_MARKUP_LANGUAGE("Business Intelligence Markup Language"), C("C"),
//  C_FOR_GRAPHICS("C for Graphics"), C_INTERMEDIATE_LANGUAGE("C Intermediate Language"), C__("C--"), C_STAR("C*"),
//  C_PLUS_PLUS("C++"), C_PLUS_PLUS_CLI("C++/CLI"), C_SHARP("C♯"), CACHÉ("Caché"),
//  CACHÉ_OBJECTSCRIPT("Caché ObjectScript"), CADENCE_SKILL("Cadence SKILL"), CAFEOBJ("CafeOBJ"), CAL("CAL"),
//  CAMELEON("Cameleon"), CAML("Caml"), CAML_LIGHT("Caml Light"), CANDLE("Candle"), CAPSL("CaPSL"),
//  CAT("Cat (linguagem de programação)"), CAYENNE("Cayenne"), CBASIC("CBASIC"),
//  CECIL__PROGRAMMING_LANGUAGE_("Cecil (programming language)"), CEEMAC("CEEMAC"), CEL("Cel"), CERNER_CCL("Cerner CCL"),
//  CÉU("Céu"), CEYLON("Ceylon"), CFENGINE("CFEngine"), CFML("CFML"), CGOL("CGOL"), CH("Ch"), CHAIN("CHAIN"),
//  CHAPEL("Chapel"), CHARITY("Charity"), CHARM("Charm"), CHARM_PLUS_PLUS("Charm++"), CHEF("chef"), CHILL("CHILL"),
//  CHINESE_BASIC("Chinese BASIC"), CHIP_8("CHIP-8"), CHIPMUNK_BASIC("Chipmunk Basic"), CHOMSKI("Chomski"),
//  CHURCH("Church"), CIAO("Ciao"), CILK("Cilk"), CILK_PLUS("Cilk Plus"), CILK_PLUS_PLUS("Cilk++"), CIMPLE("CiMPLE"),
//  CITRINE("Citrine"), CLACL("CLACL"), CLAIRE("Claire"), CLARION("Clarion"), CLEAN("Clean"), CLIPPER("Clipper"),
//  CLIPS("CLIPS"), CLIST("CLIST"), CLOJURE("Clojure"), CLP_R_("CLP(R)"), CLU("CLU"), CMS_2("CMS-2"),
//  CMU_COMMON_LISP("CMU Common Lisp"), COBOL("COBOL"), COBOL_DOTNET("COBOL.NET"), COBRA("Cobra"), CÓDIGO_G("Código G"),
//  COFFEESCRIPT("CoffeeScript"), COLA("COLA"), COLONY_FRAMEWORK("Colony Framework"), COLOR_BASIC("Color BASIC"),
//  COLORFORTH("ColorForth"), COMAL("COMAL"), COMET("Comet"), COMFY("Comfy"), COMIT("COMIT"),
//  COMMODORE_BASIC("Commodore BASIC"), COMMON_INTERMEDIATE_LANGUAGE("Common Intermediate Language"),
//  COMMON_LISP("Common Lisp"), COMMON_LISP_OBJECT_SYSTEM("Common Lisp Object System"),
//  COMPILER_DESCRIPTION_LANGUAGE("Compiler Description Language"), COMPONENT_PASCAL("Component Pascal"),
//  COMPOOL("COMPOOL"), COMPUTE_UNIFIED_DEVICE_ARCHITECTURE("Compute Unified Device Architecture"),
//  COMPUTEST("Computest"), COMTRAN("COMTRAN"), CONCURRENT_C("Concurrent C"), CONCURRENT_EUCLID("Concurrent Euclid"),
//  CONCURRENT_HASKELL("Concurrent Haskell"), CONCURRENT_ML("Concurrent ML"), CONCURRENT_PROLOG("Concurrent Prolog"),
//  CONSTRAINT_HANDLING_RULES("Constraint Handling Rules"), CONVERGE("Converge"), COOL("Cool"), COOPR("Coopr"),
//  CORAL_66("Coral 66"), CORC("CORC"), CORE_WAR("Core War"),
//  CORNELL_UNIVERSITY_PROGRAMMING_LANGUAGE("Cornell University Programming Language"), CORVISION("CorVision"),
//  COSMICOS("CosmicOS"), COWSEL("COWSEL"), CPC_CODING_SCHEME("CPC Coding scheme"), CRYPTOL("Cryptol"),
//  CRYSTAL("Crystal"), CS_4("CS-4"), CSH("Csh"), CSMP_III("CSMP III"), CSS("CSS3"), CUIS_SMALLTALK("Cuis Smalltalk"),
//  CUNEIFORM("Cuneiform"), CURL("Curl"), CURRY("Curry"), CURRY_NOTATION_SYSTEM("Curry notation system"),
//  CUSTOMER_INFORMATION_CONTROL_SYSTEM("Customer Information Control System"), CWEB("CWEB"), CYBIL("Cybil"),
//  CYCL("CycL"), CYCLONE("Cyclone"), CYTHON("Cython"), CΩ("Cω"), D("D"), DADISP("DADiSP"), DAFNY("Dafny"), DAO("Dao"),
//  DAP_FORTRAN("DAP FORTRAN"), DARKBASIC("DarkBASIC"), DARTMOUTH_ALGOL_30("Dartmouth ALGOL 30"),
//  DARTMOUTH_BASIC("Dartmouth BASIC"), DARWIN("Darwin"), DASL("DASL"),
//  DATA_LANGUAGE_INTERFACE("Data Language Interface"), DATA_ENTRY_LANGUAGE("data-entry language"),
//  DATATRIEVE("DATATRIEVE"), DBASE("DBASE"), DEADFISH("Deadfish"), DEESEL("Deesel"), DELPHI("Delphi"),
//  DELTA_COBOL("Delta COBOL"), DEPENDENCY_CONSTRAINT_LANGUAGE("Dependency Constraint Language"),
//  DEPENDENT_ML("Dependent ML"), DESIGN_BY_NUMBERS("Design By Numbers"),
//  DETERMINISTIC_PARALLEL_JAVA("Deterministic Parallel Java"), DEUTSCH_LIMIT("Deutsch limit"),
//  DEXTERITY_PROGRAMMING_LANGUAGE("Dexterity programming language"), DG_L("DG/L"), DIALECT("Dialect"), DIBOL("DIBOL"),
//  DIGITAL_COMMAND_LANGUAGE("DIGITAL Command Language"), DIPS("DIPS"), DISCIPULUS("Discipulus"),
//  DISTRIBUTED_APPLICATION_SPECIFICATION_LANGUAGE("Distributed Application Specification Language"), DOG("Dog"),
//  DOLITTLE("Dolittle"), DOPE("DOPE"), DRACO("Draco"), DRAKON("DRAKON"), DUAL("DuAL"),
//  DUP_PROGRAMMING_LANGUAGE("DUP programming language"), DYLAN("Dylan"), DYNAMO("DYNAMO"), E("E"),
//  EARSKETCH("EarSketch"), EASE("Ease"), EASY_PROGRAMMING_LANGUAGE("Easy Programming Language"),
//  EASYLANGUAGE("EasyLanguage"), EC("EC"), ECL("ECL"), ECL_PROGRAMMING_LANGUAGE("ECL programming language"),
//  EDINBURGH_IMP("Edinburgh IMP"), EDITING_GENERATOR("Editing Generator"), EFL("EFL"), EGL("EGL"), EICASLAB("EICASLAB"),
//  EIFFEL("Eiffel"), ELAN("ELAN"), ELI("ELI"), ELIXIR("Elixir"), ELLIOTT_ALGOL("Elliott ALGOL"), ELM("Elm"),
//  ELTRON_PROGRAMMING_LANGUAGE("Eltron Programming Language"), EMACS_LISP("Emacs Lisp"),
//  EMBARCADERO_DELPHI("Embarcadero Delphi"), EMBEDDED_SQL("Embedded SQL"),
//  EMBEDDED_STYLE_LANGUAGE("Embedded style language"), EMERALD("Emerald"), EMMENTAL("Emmental"), EMML("EMML"),
//  ENIAC_CODING_SYSTEM("ENIAC coding system"), ENIAC_SHORT_CODE("ENIAC Short Code"),
//  ENTERPRISE_MASHUP_MARKUP_LANGUAGE("Enterprise Mashup Markup Language"), EP_BASIC("EP-BASIC"), EPIGRAM("Epigram"),
//  EPSILON("EPSILON"), ERLANG("Erlang"), ESCHER("Escher"), ESRI_AVENUE("ESRI-Avenue"),
//  ETOYS("Etoys (linguagem de programação)"), EUCLID("Euclid"), EULER("Euler"), EULISP("EuLisp"),
//  EUPHORIA("Euphoria (linguagem de programação)"), EVENTSCRIPTS("EventScripts"),
//  EVOLUTIONARY_VIRTUAL_AGENT("Evolutionary Virtual Agent"), EX_BASIC("EX-BASIC"), EXAPT("EXAPT"), EXEC_2("EXEC 2"),
//  EXECUTIVE_SYSTEMS_PROBLEM_ORIENTED_LANGUAGE("Executive Systems Problem Oriented Language"), EXEL("EXEL"),
//  EXPECT("Expect"), EXTENDSCRIPT("ExtendScript"), EXTENSIBLE_EMBEDDABLE_LANGUAGE("Extensible Embeddable Language"),
//  F("F"), F_SCRIPT("F-Script"), F_STAR("F*"), F_SHARP("F♯"), FACE_MODELING_LANGUAGE("Face Modeling Language"),
//  FACT("FACT"), FACTOR("Factor (linguagem de programação)"), FALCON("Falcon"), FALSE("FALSE"),
//  FAMILY_OF_PROGRAMMING_LANGUAGES("Family of programming languages"),
//  FANTASY_GAMEBOOK_ENGINE("Fantasy GameBook Engine"), FANTOM("Fantom"), FARGO("FARGO"), FERITE("Ferite"), FICL("Ficl"),
//  FILEMAKER_SCRIPT("FileMaker Script"), FILETAB("Filetab"), FJÖLNIR("Fjölnir"), FL("FL"), FLACC("FLACC"),
//  FLAGSHIP("FlagShip"), FLAPJAX("Flapjax"), FLAVORS("Flavors"), FLEX("Flex"), FLOW_JAVA("Flow Java"),
//  FLOW_MATIC("Flow-Matic"), FLOWCODE("Flowcode"), FLOWGORITHM("Flowgorithm"), FOCAL("Focal"), FOCAL_69("FOCAL-69"),
//  FOIL("FOIL"), FORMAC("FORMAC"), FORMULA_LANGUAGE("Formula language"), FORTH("Forth"), FORTRAN("Fortran"),
//  FORTRESS("Fortress (linguagem de programação)"), FOXPRO("FoxPro"), FP("FP (linguagem de programação)"), FP84("FP84"),
//  FPGAC("FpgaC"), FRAME_REPRESENTATION_LANGUAGE("Frame representation language"), FREEBASIC("FreeBASIC"),
//  FREGE("Frege"), FREIBURGER_CODE("Freiburger Code"), FRENETIC("Frenetic"), FRICAS("FriCAS"), FRIL("Fril"),
//  FRINK("Frink"), FUTHARK("Futhark"), FUTUREBASIC("FutureBASIC"), FUZZY_CONTROL_LANGUAGE("Fuzzy Control Language"),
//  FX_87("FX-87"), FXML("FXML"), G_PORTUGOL("G-Portugol"), GALLINA("Gallina"), GAMBAS("Gambas"),
//  GAME_MAKER_LANGUAGE("Game Maker Language"), GAME_MAKER__STUDIO("Game Maker: Studio"),
//  GAME_ORIENTED_ASSEMBLY_LISP("Game Oriented Assembly Lisp"), GAP("GAP"), GAUSS("GAUSS"), GAWK("gawk"),
//  GDSCRIPT("GDScript"), GEMSTONE("Gemstone"), GENERAL_ALGEBRAIC_MODELING_SYSTEM("General Algebraic Modeling System"),
//  GENERAL_PURPOSE_DECLARATIVE_LANGUAGE("General-purpose declarative language"),
//  GENERALIZED_AUTOMATION_LANGUAGE("Generalized Automation Language"), GENEXUS("GeneXus"), GENIE("Genie"),
//  GEOMETRIC_DESCRIPTION_LANGUAGE("Geometric Description Language"), GEORGE("GEORGE"), GFA_BASIC("GFA BASIC"),
//  GIBIANE("Gibiane"), GLASS("Glass"), GLOBAL_ARRAYS("Global Arrays"), GLSL("GLSL"), GNU_ASSEMBLER("GNU Assembler"),
//  GNU_DATA_LANGUAGE("GNU Data Language"), GNU_E("GNU E"), GNU_GUILE("GNU Guile"), GNU_OCTAVE("GNU Octave"), GO("Go"),
//  GOAL_AGENT_PROGRAMMING_LANGUAGE("GOAL agent programming language"), GÖDEL("Gödel"), GOFER("Gofer"), GOLO("Golo"),
//  GOOGLE_APPS_SCRIPT("Google Apps Script"), GOSU("Gosu"), GPM("GPM"), GRAPHICS_LAYOUT_ENGINE("Graphics Layout Engine"),
//  GRAPHQL("GraphQL"), GRASS("GRASS"), GREEN("Green"), GREMLIN("Gremlin"), GRGEN("GrGen"), GSCRIPT("GScript"),
//  GT_DOTM("GT.M"), GUARDED_HORN_CLAUSES("Guarded Horn Clauses"), GW_BASIC("GW-BASIC"), HACK("Hack"), HAGGIS("Haggis"),
//  HAL_S("HAL/S"), HALIDE("Halide"), HAMILTON_C_SHELL("Hamilton C shell"), HAML("Haml"), HANDEL_C("Handel-C"),
//  HARBOUR("Harbour"), HARTMANN_PIPELINE("Hartmann pipeline"), HASKELL("Haskell"), HAXE("Haxe"), HC_BASIC("HC-BASIC"),
//  HELIUM("Helium"), HERMES("Hermes"), HIASM("HiAsm"),
//  HIERARCHICAL_EDITING_LANGUAGE_FOR_MACROMOLECULES("Hierarchical Editing Language for Macromolecules"),
//  HIGH_LEVEL_ASSEMBLY("High Level Assembly"), HIGH_PERFORMANCE_FORTRAN("High Performance Fortran"),
//  HIMAWARI("Himawari"), HINDAWI_PROGRAMMING_SYSTEM("Hindawi Programming System"), HOC("hoc"), HOLLYWOOD("Hollywood"),
//  HOLYC("HolyC"), HOP("Hop"), HOPE("Hope"), HOT_SOUP_PROCESSOR("Hot Soup Processor"), HPCC("HPCC"), HTML("HTML5"),
//  HUGO("Hugo"), HUME("Hume"), HY("Hy"), HYBRIS("Hybris"), HYPERFUN("HyperFun"),
//  IBM_ADVANCED_BASIC("IBM Advanced BASIC"), IBM_CASSETTE_BASIC("IBM Cassette BASIC"), IBM_DISK_BASIC("IBM Disk BASIC"),
//  IBM_PL_S("IBM PL/S"), IBM_QUERY_MANAGEMENT_FACILITY("IBM Query Management Facility"), IBM_RPG_II("IBM RPG II"),
//  IBM_RPG_III("IBM RPG III"), IBM_SYSTEM_36_BASIC("IBM System/36 BASIC"), ICI("ICI"), ICON("Icon"), ICON_L("ICon-L"),
//  ID("Id"), IDRIS("Idris"), IITRAN("IITRAN"), ILLUMINATION_SOFTWARE_CREATOR("Illumination Software Creator"),
//  ILNUMERICS_DOTNET("ILNumerics.Net"), IMP("IMP"),
//  IMPROVED_MICRODRIVE_BASIC_OPERATING_SYSTEM("Improved Microdrive BASIC Operating System"), IMPULSE_C("Impulse C"),
//  INCR_TCL("Incr Tcl"), INFORM("Inform"), INFORMATION_PROCESSING_LANGUAGE("Information Processing Language"),
//  INFORMIX_4GL("Informix-4GL"), INTEGER_BASIC("Integer BASIC"),
//  INTEL_CONCURRENT_COLLECTIONS("Intel Concurrent Collections"),
//  INTEL_PARALLEL_BUILDING_BLOCKS("Intel Parallel Building Blocks"), INTERACTIVE_C("Interactive C"),
//  INTERACTIVE_DATA_LANGUAGE("Interactive Data Language"), INTERCAL("INTERCAL"), INTERLISP("Interlisp"),
//  INTERMEDIATE_PROGRAMMING_LANGUAGE("Intermediate Programming Language"), INTERNAL_TRANSLATOR("Internal Translator"),
//  INTERPRESS("Interpress"), IO("Io"), IOKE("Ioke"), IOTA_E_JOT("Iota e Jot"), IRONLISP("IronLisp"),
//  IRONSCHEME("IronScheme"), ISETL("ISETL"), ISETLW("ISETLW"), ISLISP("ISLISP"), ISWIM("ISWIM"), ITK("Itk"),
//  IXI_LANG("Ixi lang"), IZIBASIC("Izibasic"), J("J (linguagem de programação)"), J_SHARP("J♯"),
//  JADE__BANCO_DE_DADOS_("Jade (banco de dados)"), JAL("JAL"), JANUS("Janus"), JASMIN("Jasmin"), JAVA("Java"),
//  JAVA_AGENT_DEVELOPMENT_FRAMEWORK("Java Agent Development Framework"),
//  JAVA_PERSISTENCE_QUERY_LANGUAGE("Java Persistence Query Language"), JAVAFX_SCRIPT("JavaFX Script"),
//  JAVASCRIPT("JavaScript"), JAVASERVER_PAGES_STANDARD_TAG_LIBRARY("JavaServer Pages Standard Tag Library"),
//  JEAN("JEAN"), JEEM("Jeem"), JESS("Jess"), JIMTCL("jimtcl"), JMODELICA_DOTORG("JModelica.org"),
//  JOB_CONTROL_LANGUAGE("Job Control Language"), JOCAML("JoCaml"), JOE_E("Joe-E"), JOIN_JAVA("Join Java"),
//  JOIN_CALCULUS("Join-calculus"), JOIN_PATTERN("Join-pattern"), JOLIE("Jolie"), JOSS("JOSS"), JOULE("Joule"),
//  JOVIAL("Jovial"), JOY("Joy"), JOYCE("Joyce"), JQ("Jq"), JRT("JRT"), JSCRIPT__DOTNET("JScript .NET"), JSFUCK("JSFuck"),
//  JSONIQ("JSONiq"), JSX("JSX"), JUDOSCRIPT("Judoscript"), JULIA("Julia"), JUST_BASIC("Just BASIC"), K("K"),
//  KAREL("Karel"), KAREL_PLUS_PLUS("Karel++"), KATAHDIN("Katahdin"), KAWA("Kawa"), KAYA("Kaya"),
//  KENT_RECURSIVE_CALCULATOR("Kent Recursive Calculator"), KEYKIT("Keykit"),
//  KIDS_PROGRAMMING_LANGUAGE("Kid’s Programming Language"), KINETIC_RULE_LANGUAGE("Kinetic Rule Language"), KISS("KISS"),
//  KL0("KL0"), KL1("KL1"), KLAMMERAUSDRÜCKE("Klammerausdrücke"), KLERER_MAY_SYSTEM("Klerer-May System"),
//  KM_PROGRAMMING_LANGUAGE("KM programming language"), KNITRO("KNITRO"), KOALA("Koala"), KOJO("Kojo"),
//  KOMPILER("KOMPILER"), KORN_SHELL("Korn Shell"), KRL("KRL"), KRYPTON("Krypton"), KTURTLE("KTurtle"),
//  KUKA_ROBOT_LANGUAGE("KUKA Robot Language"), L_SHARP("L Sharp"), LABVIEW("LabVIEW"), LACATRE("LACATRE"),
//  LANING_AND_ZIERLER_SYSTEM("Laning and Zierler system"), LASER_BASIC("Laser BASIC"), LASSO("Lasso"), LAVA("Lava"),
//  LAZY_K("Lazy K"), LAZY_ML("Lazy ML"), LCM("LCM"), LEAP("LEAP"), LEDA("Leda"), LEGO("LEGO"), LEXICO("Lexico"),
//  LFE("LFE"), LIBERTY_BASIC("Liberty BASIC"), LIMBO("Limbo"), LIMNOR("Limnor"), LINDA("Linda"), LINGO("Lingo"),
//  LINGUAGEM_DE_CONTROLO("Linguagem de controlo"),
//  LINGUAGEM_DE_INTEGRAÇÃO_DE_MULTIMÍDIA_SINCRONIZADA("Linguagem de Integração de Multimídia Sincronizada"),
//  LINGUAGEM_DE_MONTAGEM_X86("linguagem de montagem x86"),
//  LINGUAGEM_DE_PROGRAMAÇÃO_COMBINADA("Linguagem de Programação Combinada"),
//  LINGUAGEM_DE_PROGRAMAÇÃO_OAK("Linguagem de programação Oak"), LINGUAGEM_LADDER("linguagem ladder"), LINKS("Links"),
//  LINOTTE("Linotte"), LIS("LIS"), LISA("LISA"), LISAAC("Lisaac"), LISP("Lisp"), LISP_MACHINE_LISP("Lisp Machine Lisp"),
//  LISPWORKS("LispWorks"), LITE_C("Lite-C"), LITHE("Lithe"), LITTLE_B("Little b"), LIVECODE("LiveCode"),
//  LIVESCRIPT("LiveScript"), LOCOMOTIVE_BASIC("Locomotive BASIC"), LOGIC_BASIC("Logic Basic"), LOGLAN("Loglan"),
//  LOGLAN_82("Loglan 82"), LOGLAN_88("Loglan 88"), LOGO("Logo"), LOGTALK("Logtalk"), LOLCODE("LOLCODE"), LOOM("LOOM"),
//  LOTUSSCRIPT("LotusScript"), LPC("LPC"), LSE("LSE"), LTR("LTR"), LUCID("Lucid"), LUNA("Luna"),
//  LUSH("Lush (linguagem de programação)"), LUSTRE("Lustre"), LYNX("Lynx"), LZX("LZX"), M("M"), M_SHARP("M#"),
//  M2001("M2001"), M4("m4"), MACINTOSH_COMMON_LISP("Macintosh Common Lisp"), MACLISP("Maclisp"), MACROML("MacroML"),
//  MAD("MAD"), MAGIK("Magik"), MAGMA_COMPUTER_ALGEBRA_SYSTEM("Magma computer algebra system"),
//  MAI_BASIC_FOUR("MAI Basic Four"), MALBOLGE("Malbolge"), MAMA("Mama"), MANA("Mana"),
//  MANAGED_EXTENSIONS_FOR_C_PLUS_PLUS("Managed Extensions for C++"),
//  MANCHESTER_SCENE_DESCRIPTION_LANGUAGE("Manchester Scene Description Language"), MAPLE("Maple"), MAPPER("MAPPER"),
//  MARK_IV("MARK IV"), MARY("Mary"), MATH_MATIC("MATH-MATIC"), MATHCAD("Mathcad"), MATHEMATICA("Mathematica"),
//  MATLAB("MATLAB"), MATRIX_MATH("MATRIX MATH"), MAUDE_SYSTEM("Maude system"), MAXSCRIPT("Maxscript"),
//  MAYA_EMBEDDED_LANGUAGE("Maya Embedded Language"), MCPL("MCPL"), MDL("MDL"), MERCURY("Mercury"), MESA("Mesa"),
//  MESSAGE_FORMAT_LANGUAGE("Message Format Language"), MET_ENGLISH("Met English"), METAFONT("METAFONT"),
//  METAOBJECT_PROTOCOL("Metaobject Protocol"), METAPOST("MetaPost"),
//  METAQUOTES_LANGUAGE_MQL4_MQL5("MetaQuotes Language MQL4/MQL5"), MEXSCRIPT("MexScript"), MICRO_LUA_DS("Micro Lua DS"),
//  MICROMONDES("MicroMondes"), MICROSOFT_BASIC("Microsoft BASIC"),
//  MICROSOFT_MACRO_ASSEMBLER("Microsoft Macro Assembler"), MICROSOFT_SMALL_BASIC("Microsoft Small Basic"),
//  MIDAS("MIDAS"), MIIS("MIIS"), MILK("Milk"), MIMIC("MIMIC"), MIND("Mind"), MINID("MiniD"), MIRAH("Mirah"),
//  MIRANDA("Miranda"), MIRC_SCRIPT("MIRC script"), MIXAL("MIXAL"), MIZAR_SYSTEM("Mizar system"), ML("ML"), MLAB("MLAB"),
//  MLISP("MLisp"), MOBILE_BASIC("Mobile BASIC"), MOCKLISP("Mocklisp"), MODELICA("Modelica"),
//  MODERNPASCAL("ModernPascal"), MODULA("Modula"), MODULA_2("Modula-2"), MODULA_2_PLUS("Modula-2+"),
//  MODULA_3("Modula-3"), MOLOG("MOLOG"), MONDRIAN("Mondrian"), MONKEY_X("Monkey X"), MOO("MOO"), MOUSE("Mouse"),
//  MPD("MPD"), MS_BASIC_FOR_MACINTOSH("MS BASIC for Macintosh"), MST_WORKSHOP("MST Workshop"), MSX_BASIC("MSX-BASIC"),
//  MUDLLE("Mudlle"), MULTILISP("MultiLisp"), MUMPS("MUMPS"), MUSIC_MARKUP_LANGUAGE("Music Markup Language"),
//  NADESHIKO("Nadeshiko"), NAPIER88("Napier88"), NASM("NASM"), NATO_DOT0_PLUS55_PLUS3D("Nato.0+55+3d"),
//  NATURAL("NATURAL"), NCL("NCL"), NEAT("NEAT"), NEKO("Neko"), NEMERLE("Nemerle"),
//  NEO_SIGN_0F_MISERY("Neo Sign 0f Misery"), NESC("nesC"), NESL("NESL"),
//  NESSUS_ATTACK_SCRIPTING_LANGUAGE("Nessus Attack Scripting Language"), NET_DOTDATA("Net.Data"), NETLOGO("NetLogo"),
//  NETREXX("NetRexx"), NEWLISP("NewLISP"), NEWP("NEWP"), NEWSPEAK("Newspeak"), NEWSQUEAK("Newsqueak"),
//  NEWTONSCRIPT("NewtonScript"), NEXT_BYTE_CODES("Next Byte Codes"), NIAL("Nial"), NICE("Nice"), NICKLE("Nickle"),
//  NIL("NIL"), NIM("Nim"), NOCK("Nock"), NOOP("Noop"), NORD_PROGRAMMING_LANGUAGE("Nord Programming Language"),
//  NORTH_AMERICAN_PRESENTATION_LEVEL_PROTOCOL_SYNTAX("North American Presentation Level Protocol Syntax"),
//  NOT_EXACTLY_C("Not eXactly C"), NPL("NPL"), NQC("NQC"), NQP("NQP"), NS_BASIC("NS Basic"), NU("Nu"),
//  NULLSOFT_SCRIPTABLE_INSTALL_SYSTEM("Nullsoft Scriptable Install System"), NWSCRIPT("NWScript"), O_XML("o:XML"),
//  OAKLISP("Oaklisp"), OBERON("Oberon"), OBERON_2("Oberon-2"), OBIX("Obix"), OBJ("OBJ"), OBJ2("OBJ2"), OBJ3("OBJ3"),
//  OBJECT_OBERON("Object Oberon"), OBJECT_PASCAL("Object Pascal"), OBJECT_REXX("Object REXX"),
//  OBJECT_ORIENTED_CSS("Object-oriented CSS"), OBJECT_PL_SQL("Object-PL/SQL"), OBJECTIVE_C("Objective-C"),
//  OBJECTIVE_J("Objective-J"), OBJECTLOGO("ObjectLOGO"), OBJECTPAL("ObjectPAL"), OBJLOG("Objlog"), OBJVLISP("ObjVlisp"),
//  OBLIQ("Obliq"), OCAML("OCaml"), OCCAM("Occam"), OCCAM_Π("Occam-π"), OCTAVE("Octave"), OML("OML"),
//  OMNIBAC_SYMBOLIC_ASSEMBLER("OMNIBAC Symbolic Assembler"), OMNIMARK("OmniMark"), OOC("Ooc"), OOK("Ook!"), OPA("Opa"),
//  OPAL("Opal"), OPEN_ROBERTA("Open Roberta"), OPEN_VIRTUAL_MACHINE_LANGUAGE("Open Virtual Machine Language"),
//  OPENCL("OpenCL"), OPENGL_ES_SHADING_LANGUAGE("OpenGL ES Shading Language"), OPENMODELICA("Openmodelica"),
//  OPENMX("OpenMx"), OPS5("OPS5"), OPTIMJ("OptimJ"), ORC("Orc"), ORCA_MODULA_2("ORCA/Modula-2"), ORIEL("Oriel"),
//  ORWELL("Orwell"), OTTOQL("OttoQL"), OTX("OTX"), OX("Ox"), OXYGENE("Oxygene"), OZ("Oz"), DRSCHEME("DrScheme"), P("P"),
//  P_STAR("P*"), P_SHARP("P#"), P4("P4"), PACT("PACT"), PAL("PAL"), PAN("Pan"), PANORAMIC("PANORAMIC"),
//  PARADOX("Paradox"), PARASAIL("ParaSail"), PARI_GP("PARI/GP"), PARLOG("Parlog"), PARSER("Parser"), PASCAL("Pascal"),
//  PASCALABC_DOTNET("PascalABC.NET"), PAUSCAL("Pauscal"), PCASTL("PCASTL"), PEARL("PEARL"), PEOPLECODE("PeopleCode"),
//  PERL("Perl"), PERL_DATA_LANGUAGE("Perl Data Language"), PETR("Petr"), PFORTH("Pforth"), PHARO("Pharo"),
//  PHP4DELPHI("Php4delphi"), PHROGRAM("Phrogram"),
//  PHYSICALLY_BASED_RENDERING_MODELING_LANGUAGE("Physically Based Rendering Modeling Language"),
//  PIC_MICRO_PASCAL("Pic Micro Pascal"), PICO("Pico (linguagem de programação)"), PICOLISP("PicoLisp"), PICT("Pict"),
//  PIET("Piet"), PIKE("Pike"), PIKT("PIKT"), PILOT("PILOT"), PIPELINE_PILOT("Pipeline Pilot"), PIXIE("Pixie"),
//  PIXILANG("Pixilang"), PIZZA("Pizza (linguagem de programação)"), PL_11("PL-11"), PL_0("PL/0"), PL_8("PL/8"),
//  PL_C("PL/C"), PL_I("PL/I"), PL_M("PL/M"), PL_P("PL/P"), PL_PGSQL("PL/pgSQL"), PL_SQL("PL/SQL"), PL_X("PL/X"),
//  PL360("PL360"), PLANC("PLANC"), PLANKALKÜL("Plankalkül"), PLANNER("Planner"), PLEX("PLEX"), PLEXIL("PLEXIL"),
//  PLIANT("Pliant"), PLUS("Plus"), PNUTS("Pnuts"), POLYMORPHIC_PROGRAMMING_LANGUAGE("Polymorphic Programming Language"),
//  POLYMORPHIC_RECURSION("Polymorphic recursion"), POLYPHONIC_C_SHARP("Polyphonic C#"), PONIE("PONIE"), PONY("Pony"),
//  POP_11("POP-11"), POP_2("POP-2"), POPLOG("Poplog"), PORTABLE_STANDARD_LISP("Portable Standard Lisp"),
//  PORTAL("Portal"), PORTLET("Portlet"), POSITY("Posity"), POSTSCRIPT("PostScript"), POSXML("POSXML"),
//  POTION("Potion (linguagem de programação)"), POTTERSWHEEL("PottersWheel"), POW("POW!"), POWERBASIC("PowerBASIC"),
//  POWERHOUSE("PowerHouse"), POWERSCRIPT("PowerScript"), PPL("PPL"), PQL("PQL"), PRASPEL("Praspel"), PRINT("PRINT"),
//  PRO_STARC("Pro*C"), PROCESSING("Processing"), PROCESSING_DOTJS("Processing.js"),
//  PROCYON("Procyon (linguagem de programação)"), PROFILE_SCRIPTING_LANGUAGE("Profile Scripting Language"),
//  PROGRAM_COMPOSITION_NOTATION("Program Composition Notation"),
//  PROGRAMMABLE_COMMAND_LANGUAGE("Programmable Command Language"),
//  PROGRAMMABLE_MACRO_LANGUAGE("Programmable Macro Language"),
//  PROGRAMMATION_AUTOMATIQUE_DES_FORMULES("Programmation Automatique des Formules"),
//  PROGRAMMING_COMPUTABLE_FUNCTIONS("Programming Computable Functions"),
//  PROGRAMMING_LANGUAGE_FOR_BUSINESS("Programming Language for Business"),
//  PROGRAMMING_LANGUAGE_FOR_DISTRIBUTED_SYSTEMS("Programming Language for Distributed Systems"),
//  PROGRAMMING_WITH_BIG_DATA_IN_R("Programming with Big Data in R"), PROGRAPH("Prograph"), PROGRES("PROGRES"),
//  PROGRESS_4GL("Progress 4GL"), PROJECT_BUILDER("Project Builder"), PROLOG("Prolog"), PROMAL("PROMAL"), PROSA("PROSA"),
//  PROSE_MODELING_LANGUAGE("PROSE modeling language"), PROSET("ProSet"), PROTEL("Protel"), PROTEUS("Proteus"),
//  PROTOTYPE_VERIFICATION_SYSTEM("Prototype Verification System"), PROVA("Prova"), PROVIDEX("ProvideX"), PSAKE("Psake"),
//  PTOLEMY_PROJECT("Ptolemy Project"), PTQL("PTQL"), PURE("Pure"), PUREBASIC("PureBasic"), PV_WAVE("PV-Wave"),
//  PY("Py (linguagem de programação)"), PYLINDA("PyLinda"), PYREX("Pyrex"), PYTHON_3("Python 3"),
//  PYTHON_FOR_S60("Python for S60"), PYUNIT("PyUnit"), Q("Q"), QALB("Qalb"), QB64("QB64"), QBASIC("QBasic"), QI("Qi"),
//  QML("QML"), QORE("Qore"), QU("Qu"), QUARTZ_COMPOSER("Quartz Composer"), QUEL("QUEL"), QUICKBASIC("QuickBASIC"),
//  QUICKPASCAL("QuickPascal"), QUIKTRAN("QUIKTRAN"), QUILL("QUILL"), R("R"), R_PLUS_PLUS("R++"), RAKU("Raku"),
//  RAPID("RAPID"), RAPIRA("Rapira"), RAPTOR("Raptor"), RASCALMPL("RascalMPL"), RATFOR("Ratfor"),
//  RATIONAL_MODELING_LANGUAGE("Rational Modeling Language"), RBASIC("RBASIC"), RC("rc"), RCML("RCML"),
//  READ_PRINT("READ/PRINT"), REAKTOR("Reaktor"), REAL_TIME_BIDDING("Real-time bidding"), REALBASIC("RealBasic"),
//  REALTIME_PROGRAMMING_LANGUAGE("Realtime Programming Language"), REBOL("REBOL"), RED("Red"), REFAL("Refal"),
//  REGIONAL_ASSEMBLY_LANGUAGE("Regional Assembly Language"), REIA("Reia"), REX("Rex"), REXX("REXX"), RGSS("RGSS"),
//  RING("Ring"), RISCLUA("RiscLua"), ROBIC("Robic"), ROBOT_BATTLE("Robot Battle"), ROBOTC("Robotc"),
//  ROCHESTER_ASSEMBLER("Rochester assembler"), ROCKY_MOUNTAIN_BASIC("Rocky Mountain BASIC"), ROOP("ROOP"), ROOT("ROOT"),
//  ROY("Roy (linguagem de programação)"), RPAL("Rpal"), RPG("RPG"), RPG_CODE("RPG Code"), RPG_IV("RPG IV"),
//  RPG_400("RPG/400"), RPL("RPL"), RTL_2("RTL/2"), RTML("RTML"), RUN_BASIC("Run BASIC"), RUR_PLE("RUR-PLE"),
//  S("S (linguagem de programação)"), S_PLUS("S-PLUS"), S_SL_PROGRAMMING_LANGUAGE("S/SL programming language"), S2("S2"),
//  S3("S3"), SABRETALK("SabreTalk"), SAC_PROGRAMMING_LANGUAGE("SAC programming language"), SAIL("SAIL"), SAKO("SAKO"),
//  SALSA("SALSA"), SAM76("SAM76"), SAMPL("SAMPL"), SAS("SAS"), SAS_LANGUAGE("SAS language"), SASL("SASL"), SASS("Sass"),
//  SATHER("Sather"), SAWZALL("Sawzall"), SCALA("Scala"), SCHEME("Scheme"),
//  SCIENTIFIC_VECTOR_LANGUAGE("Scientific Vector Language"), SCILAB("Scilab"), SCM("SCM"), SCOL("Scol"),
//  SCRATCH("Scratch"), SCRIPT_DOTNET("Script.NET"), SCRIPTOL("Scriptol (linguagem de programação)"),
//  SECURE_OPERATIONS_LANGUAGE("Secure Operations Language"), SED("sed"), SEED7("Seed7"), SELF("Self"), SENSE("Sense"),
//  SENSETALK("SenseTalk"), SEQUENCEL("SequenceL"), SEQUENTIELLE_FORMELÜBERSETZUNG("Sequentielle Formelübersetzung"),
//  SETL("SETL"), SETL2("SETL2"), SHAKESPEARE("Shakespeare"), SHEN("Shen"), SHEX("ShEx"), SHORT_CODE("Short Code"),
//  SIEVE("Sieve"), SIGNAL("SIGNAL"), SIMPLE("Simple"),
//  SIMPLE_YET_POWERFUL_SCRIPTING_LANGUAGE("Simple Yet Powerful Scripting Language"), SIMUL("Simul"), SIMULA("Simula"),
//  SIMULINK("Simulink"), SING_SHARP("Sing#"), SINGULARITY("Singularity"), SISAL("SISAL"), SISTEMA_A_0("Sistema A-0"),
//  SISTEMA_PROGRAMAÇÃO_MOZART("Sistema Programação Mozart"), SK8("SK8"), SKILL("SKILL"), SL5("SL5"), SLATE("Slate"),
//  SLIP("SLIP (linguagem de programação)"), SMALL("SMALL"), SMALLBASIC("SmallBASIC"), SMALLTALK("Smalltalk"),
//  SMART_PASCAL("Smart Pascal"), SMIL_TIMESHEETS("SMIL Timesheets"), SNAP("Snap!"), SNAP4ARDUINO("Snap4Arduino"),
//  SNOBOL_4("SNOBOL 4"), SNOSTORM("Snostorm"), SOLIDITY("Solidity"), SOLIDTHINKING_EMBED("SolidThinking Embed"),
//  SORT_MERGE_GENERATOR("Sort Merge Generator"), SP_K("SP/k"), SPACE_PROGRAMMING_LANGUAGE("Space Programming Language"),
//  SPARK("SPARK"), SPEAKEASY("Speakeasy"), SPEC_SHARP("Spec#"), SPEEDCODING("Speedcoding"), SPICE_LISP("Spice Lisp"),
//  SPIDERBASIC("SpiderBasic"), SPLIT_C("Split-C"), SPOON("Spoon"), SQL("SQL"), SQL_PSM("SQL/PSM"), SQLPL("SQLPL"),
//  SQUEAK("Squeak"), SQUIRREL("Squirrel"), SR("SR"), STADYN("StaDyn"), STAGECAST_CREATOR("Stagecast Creator"),
//  STAN("Stan"), STANDARD_ML("Standard ML"), STANDARD_ML_OF_NEW_JERSEY("Standard ML of New Jersey"),
//  STANISLAUS("Stanislaus"), STARLOGO("StarLogo"), STATA("Stata"), STATEFLOW("Stateflow"),
//  STEEL_BANK_COMMON_LISP("Steel Bank Common Lisp"), STELLA("STELLA"), STENCYL("Stencyl"), STOS_BASIC("STOS BASIC"),
//  STRATEGO_XT("Stratego/XT"), STRONGTALK("Strongtalk"), STYLUS("Stylus"), SUBL("SubL"), SUBTEXT("Subtext"), SUE("Sue"),
//  SUNEIDO_PROGRAMMING_LANGUAGE("Suneido programming language"), SUPERBASE_DATABASE("Superbase database"),
//  SUPERBASIC("SuperBASIC"), SUPERLOGO("Superlogo"), SUPERMUMPS("SuperMumps"), SUPERPASCAL("SuperPascal"),
//  SUPERPLAN("Superplan"), SWAF("SWAF"), SWI_PROLOG("SWI-Prolog"), SWIFT("Swift"), SYMPL("SYMPL"),
//  SYNTAX_DEFINITION_FORMALISM("Syntax Definition Formalism"), SYSTEMVERILOG("SystemVerilog"), T("T"), TACPOL("TACPOL"),
//  TADS("TADS"), TEA("Tea"), TECO("TECO"), TEKKIE_UNI("Tekkie Uni"), TELCOMP("TELCOMP"),
//  TEXT_EXECUTIVE_PROGRAMMING_LANGUAGE("Text Executive Programming Language"),
//  TEXT_PROCESSING_UTILITY("Text Processing Utility"), TEXTO_ESTRUTURADO("Texto estruturado"), THINBASIC("ThinBasic"),
//  THINK_C("THINK C"), THUE("Thue"), TI_BASIC("TI BASIC"), TIMBER("Timber"), TINY_BASIC("Tiny BASIC"),
//  TINY_PROGRAMMING_LANGUAGE("Tiny programming language"), TJS2("TJS2"), TLA_PLUS("TLA+"), TMG("TMG"), TNSDL("TNSDL"),
//  TOM("Tom"), TOMVIEW("TOMVIEW"), TOONTALK("Toontalk"), TORQUE_GAME_ENGINE("Torque Game Engine"),
//  TOUCHDESIGNER("TouchDesigner"), TOUCHDEVELOP("TouchDevelop"), TRAC("TRAC"),
//  TRADE_SPACE_VISUALIZER("Trade Space Visualizer"), TRANSACT_SQL("Transact-SQL"),
//  TRANSACTION_APPLICATION_LANGUAGE("Transaction Application Language"), TREE_META("TREE-META"), TRITIUM("Tritium"),
//  TRUE_BASIC("True BASIC"), TTM("TTM"), TTSNEO("TTSneo"), TURBO_BASIC("Turbo Basic"), TURBO_C_PLUS_PLUS("Turbo C++"),
//  TURBO_PASCAL("Turbo Pascal"), TURBO_PASCAL_OOP("Turbo Pascal OOP"), TURBO_BASIC_XL("Turbo-Basic XL"),
//  TURBO51("Turbo51"), TURING("Turing"), TURING_PLUS("Turing+"), TUTOR("TUTOR"), TWELF("Twelf"), TXL("TXL"),
//  TYNKER("Tynker"), TYPED_ASSEMBLY_LANGUAGE("Typed assembly language"), TYPESCRIPT("TypeScript"), UCBLOGO("UCBLogo"),
//  UCSD_PASCAL("UCSD Pascal"), UML("UML"), UMPLE("Umple"), UNCOL("UNCOL"), UNICODE("UNICODE"), UNICON("Unicon"),
//  UNIFACE("Uniface"), UNIFIED_PARALLEL_C("Unified Parallel C"), UNITY("UNITY"),
//  UNIVERSAL_TEST_SPECIFICATION_LANGUAGE("Universal Test Specification Language"), UNLAMBDA("Unlambda"),
//  UNOBTRUSIVE_JAVASCRIPT("Unobtrusive JavaScript"), UNREALSCRIPT("UnrealScript"), UR("Ur"), URBI("URBI"),
//  URBISCRIPT("urbiscript"), UWSC("UWSC"), VALA("Vala"), VAX_MACRO("VAX Macro"), VERILOG("Verilog"), VHDL("VHDL"),
//  VILNIUS_BASIC("Vilnius BASIC"), VIM_SCRIPT("Vim script"), VISICALC("VisiCalc"), VISUAL_BASIC("Visual Basic"),
//  VISUAL_BASIC_FOR_APPLICATIONS("Visual Basic for Applications"), VISUAL_FOXPRO("Visual FoxPro"),
//  VISUAL_J_PLUS_PLUS("Visual J++"), VISUAL_LOGIC("Visual Logic"), VISUAL_PROLOG("Visual Prolog"),
//  VISUAL_T_SHARP("Visual T#"), VON_NEUMANN_AND_GOLDSTINE_GRAPHING_SYSTEM("Von Neumann and Goldstine graphing system"),
//  VSXU("VSXu"), VVVV("Vvvv"), WATFIV("WATFIV"), WAVEGL("WaveGL"), WEB("Web"), WEBMETHODS_FLOW("webMethods Flow"),
//  WHILEY("Whiley"), WHIRLWIND_ASSEMBLER("Whirlwind assembler"), WHITESPACE("Whitespace"), WICS("WICS"),
//  WINDOWS_APP_STUDIO("Windows App Studio"), WIRING("Wiring"), WLANGUAGE("WLanguage"), WMLSCRIPT("WMLScript"),
//  WOLFRAM("Wolfram"), WORDBASIC("WordBASIC"), WSFN("WSFN"), WYVERN("Wyvern"), X_PLUS_PLUS("X++"), X10("X10"),
//  XACML("XACML"), XAML("XAML"), XBASE_PLUS_PLUS("XBase++"), XBASIC("XBasic"), XBLITE("XBLite"),
//  XC_PROGRAMMING_LANGUAGE("XC Programming Language"), XCALABLEMP("XcalableMP"), XCORE_XS1("XCore XS1"),
//  XHARBOUR("XHarbour"), XL("XL"), XMTC("XMTC"), XOJO("Xojo"), XOTCL("XOTcl"), XPATH("XPath"), XPL("XPL"), XPL0("XPL0"),
//  XPROC("XProc"), XPROFAN("XProfan"), XSB("XSB"), XSLT("XSLT"), XTEND("Xtend"), XUL("XUL"), XUPDATE("XUpdate"),
//  YELLOW("Yellow"), YOIX("Yoix"), YORICK("Yorick"), Z_PLUS_PLUS("Z++"), ZEBRA("Zebra"), ZENO("Zeno"),
//  ZETALISP("ZetaLisp"), ZHPY("ZhPy"), ZIG("Zig"), ZONNON("Zonnon"), ZOPL("ZOPL"), ZPL("ZPL");
//
//  @Getter
//  private String descricao;
//
//}
